_defaults:
  linux: &linux
    os: linux
    dist: xenial
    sudo: required

language: java

install:
  - sudo apt-get install openjdk-8-jdk-headless
  - wget http://services.gradle.org/distributions/gradle-2.13-bin.zip
  - unzip -qq gradle-2.13-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.13
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v

cache:
  directories:
  - $HOME/.gradle/caches/
